POST http://onlinefooddeliverybackend.test/api/customer/register HTTP/1.1
content-type: application/json
Accept: application/json

{
    "first_name": "Khushnood",
    "surname": "Khan",
    "email": "khush11@email.com",
    "landline_phone": "07415031519",
    "mobile_phone": "07415031519",
    "address_line_1": "18 Mansfield Road",
    "town": "Yardley",
    "city": "Birmingham",
    "county": "West Midlands",
    "postcode": "B25 8LY",
    "password": "password",
    "password_confirmation": "password"
}