PUT http://onlinefooddeliverybackend.test/api/customer/profile/update HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer 3|BH7nP4fbokmX1JmH5a6A73w1N6cNJZlqvAGsXTS8800f21cf

{
    "first_name": "Khushnood",
    "surname": "Ahmed Khan",
    "landline_phone": "07415031519",
    "mobile_phone": "07415031519",
    "address_line_1": "8 Allcroft Road",
    "town": "Tyseley",
    "city": "Birmingham",
    "county": "West Midlands",
    "postcode": "B25 8LY",
    "password": "password",
    "password_confirmation": "password"
}