POST http://onlinefooddeliverybackend.test/api/delivery_drivers/vehicle HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer 19|ZrGojb115RxvEVojCm2adMkttvQY1YdhqhewsKQQd36a305f

{
    "type": "CAR",
    "registration_number": "AB11 CDE",
    "year": 2024,
    "status": "INACTIVE",
    "delivery_driver_id": "9d4e715c-09da-40b5-97bb-f3690775c73b"
}