POST http://onlinefooddeliverybackend.test/api/user/register HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer 16|fOktTnabANBQsRyHpAAcJn336F5gcsj8tnL6znlr2b6f7159

{
    "first_name": "Ahmad",
    "surname": "Ali",
    "email": "ahmad.ali.adminab@email.com",
    "password": "password",
    "password_confirmation": "password",
    "user_type": 1
}