GET http://onlinefooddeliverybackend.test/api/delivery_vehicles HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer 10|plnIb9VNt5mKzMmolBoQqVDCadhUj48XkVcDyqH08712d6b2

###

POST http://onlinefooddeliverybackend.test/api/delivery_vehicles HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer 10|plnIb9VNt5mKzMmolBoQqVDCadhUj48XkVcDyqH08712d6b2

{
    "delivery_driver_id": "9d4e715c-09da-40b5-97bb-f3690775c73b",
    "type": "ELECTRIC_BIKE",
    "registration_number": "",
    "year": 2014,
    "status": "ACTIVE"
}

###

GET http://onlinefooddeliverybackend.test/api/delivery_vehicles/9d4e89f6-854a-48e3-9ce1-99bef088ff76 HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer 10|plnIb9VNt5mKzMmolBoQqVDCadhUj48XkVcDyqH08712d6b2

###

PUT http://onlinefooddeliverybackend.test/api/delivery_vehicles/9d4e89f6-854a-48e3-9ce1-99bef088ff76 HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer 10|plnIb9VNt5mKzMmolBoQqVDCadhUj48XkVcDyqH08712d6b2

{
    "delivery_driver_id": "9d4e715c-09da-40b5-97bb-f3690775c73b",
    "type": "ELECTRIC_BIKE",
    "registration_number": "",
    "year": 2019,
    "status": "ACTIVE"
}

###

DELETE http://onlinefooddeliverybackend.test/api/delivery_vehicles/9d4e89f6-854a-48e3-9ce1-99bef088ff76 HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer 10|plnIb9VNt5mKzMmolBoQqVDCadhUj48XkVcDyqH08712d6b2

###

POST http://onlinefooddeliverybackend.test/api/delivery_vehicles/documents/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Accept: application/json
Authorization: Bearer 10|plnIb9VNt5mKzMmolBoQqVDCadhUj48XkVcDyqH08712d6b2

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

GET http://onlinefooddeliverybackend.test/api/delivery_vehicles/9d50c061-0f65-4ad0-93ea-744e0a0e2a3a/documents HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer 10|plnIb9VNt5mKzMmolBoQqVDCadhUj48XkVcDyqH08712d6b2

###

GET http://onlinefooddeliverybackend.test/api/delivery_vehicles/documents/9b535597-f0e7-4a53-9a8a-d51e133768c1/download HTTP/1.1
content-type: application/json
Accept: image/png
Authorization: Bearer 10|plnIb9VNt5mKzMmolBoQqVDCadhUj48XkVcDyqH08712d6b2

