POST http://onlinefooddeliverybackend.test/api/vendors/register HTTP/1.1
content-type: application/json
Accept: application/json

{
    "first_name": "John",
    "surname": "Doe",
    "email": "vendor@email.com",
    "landline_phone": "01215064000",
    "mobile_phone": "07541254789",
    "address_line_1": "Flat 34 Lime Court, Showell Green Lane",
    "town": "Sparkhill",
    "city": "Birmingham",
    "county": "West Midlands",
    "postcode": "B11 4JT",
    "status": "WORKING",
    "password": "password",
    "password_confirmation": "password",
    "business_name": "Terry's One Stop Shop",
    "trading_name": "Terry's One Stop Shop"
}

###

POST http://onlinefooddeliverybackend.test/api/vendors/login HTTP/1.1
content-type: application/json
Accept: application/json

{
    "email": "vendor@email.com",
    "password": "password"
}

###

GET http://onlinefooddeliverybackend.test/api/vendors/profile/show HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer 13|p7ID9kum0WK6DFDqRDDiESSej7R27pyZSU7ooXsO34a2f54e

{
    
}

###

PUT http://onlinefooddeliverybackend.test/api/vendors/profile/update HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer 13|p7ID9kum0WK6DFDqRDDiESSej7R27pyZSU7ooXsO34a2f54e

{
    "first_name": "Johnsonn",
    "surname": "Doe",
    "email": "John.Doe@email.com",
    "landline_phone": "01215064000",
    "mobile_phone": "07541254789",
    "address_line_1": "Flat 34 Lime Court, Showell Green Lane",
    "town": "Sparkhill",
    "city": "Birmingham",
    "county": "West Midlands",
    "postcode": "B11 4JT",
    "status": "WORKING"
}

###

PUT http://onlinefooddeliverybackend.test/api/vendors/profile/update HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Accept: application/json
Authorization: Bearer 13|p7ID9kum0WK6DFDqRDDiESSej7R27pyZSU7ooXsO34a2f54e

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="logo"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

GET http://onlinefooddeliverybackend.test/api/vendors/9d5221c9-893f-4687-87c1-9b2092321617 HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer 13|p7ID9kum0WK6DFDqRDDiESSej7R27pyZSU7ooXsO34a2f54e

{
    
}

###

GET http://onlinefooddeliverybackend.test/api/vendors HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer 13|p7ID9kum0WK6DFDqRDDiESSej7R27pyZSU7ooXsO34a2f54e

{
    
}

###

PUT http://onlinefooddeliverybackend.test/api/vendors/9d5221c9-893f-4687-87c1-9b2092321617 HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer 13|p7ID9kum0WK6DFDqRDDiESSej7R27pyZSU7ooXsO34a2f54e

{
    "first_name": "John",
    "surname": "Doe",
    "email": "John.Doe@email.com",
    "landline_phone": "01215064000",
    "mobile_phone": "07541254789",
    "address_line_1": "Flat 34 Lime Court, Showell Green Lane",
    "town": "Sparkhill",
    "city": "Birmingham",
    "county": "West Midlands",
    "postcode": "B11 4JT",
    "status": "WORKING"
}



